server:
  port: 8080

spring:
  application:
    name: docreader

  datasource:
    url: jdbc:postgresql://localhost:5432/docreader
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  # Allow our manual AppConfig beans to override autoconfigured ones
  main:
    allow-bean-definition-overriding: true

  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
      - org.springframework.ai.model.ollama.autoconfigure.OllamaChatAutoConfiguration
      - org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

  ai:
    openai:
      api-key: ${GROQ_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.3
          max-tokens: 1024

    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text

logging:
  level:
    com.docmind: DEBUG
    org.springframework.ai: INFO

spring.servlet.multipart:
  max-file-size: 50MB
  max-request-size: 50MB
